### PR TITLE
Laceration and repair

### PR DESCRIPTION
**Pull request by laylaAbu**
This is an updated version of an older PV card titled Sutured material published in 07/01/2017

### CODE REVIEW

**Comment by laylaAbu** [comment]
| **SUTURE TYPE**  | **Time of Effective
Tensile Strength**  |  **Time to
Absorption** | **Reactivity**  |
|---|---|---|---|
|  Prolene  |  indefinite |  non absorbable  |  low  |
|  Nylon   |  gradual loss  |  non absorbable  |  low  |
|  Silk  |  gradual loss |  non absorbable  |  high  |
|  Fast absorbing gut |  7 days  |  21-42 days |  high |
|  Vicryl Rapide |  5-14 days |  42 days |  high  |
|  Monocryl |  7-14 days  |  91-119 days  |  high  |
|  Vicryl |  14-28 days |  56-70 days  |  high  |
|  Chromic Gut |  21-28 days  |  90 days  |  high |

**Comment by laylaAbu** [comment]
**SPECIAL CONSIDERATION**
| **LOCATION** | **CONCERN** | **TREATMENT** |
|---|---|---|
| Eyelid margin | Requires careful
approximation | Ophthalmology consult for repair |
| Medial canthus
of eye  | Lacrimal duct location | Ophthalmology consult for repair  |
| Vermillion
border of lip | Requires careful
approximation | Consider consulting Oral Maxillofacial
Surgery or Plastics |
| Mammalian
bites  | Risk for infection,
especially of the
hands:
Human > Cat > Dog  |  • **Antibiotics:** Amoxicillin-clavulanate
(Cochrane: Antibiotics not warranted
for uncomplicated dog bites to non-hand
areas of the body [1].)
• Do not close wounds, especially if
puncture-like. |

**Comment by jvoros** [comment]
Thank you for trying! The GitHub process is a bit...well...technical. I know that it is a barrier.

Your markdown format for the card looks perfect. Exactly what we want. I would start a folder on your computer. The name of the folder needs to be related to the card title, eg 'laceration-suture-material' or something along those lines. Inside that folder you need to have a 'card.md' file, which is the file that you write your markdown in. Images can be added to the folder to show up in the markdown when it is displayed on the web.

This wiki shows how to build the card: https://github.com/aliemteam/aliemcards/wiki/How-to-Build-an-ALiEM-Card
This wiki shows how to add the card to the project and make a pull request: https://github.com/aliemteam/aliemcards/wiki/Tutorial:-Adding-a-Card

Let me know if that helps and what problems arise next.

**Comment by dsifford** [comment]
What's the status on this? Anything I can help with?

**Comment by laylaAbu** [comment]
Derek,
I would like some help with uploading images.

Layla

**Comment by dsifford** [comment]
@laylaAbu Did you understand what @jvoros requested?

The markdown that you posted as a comment just needs to be uploaded to a `card.md` file in a folder titled `laceration-and-repair`. Once that's done, all you need to do is drag and drop the images in that folder and name them according to the guidelines spelled out in the wiki.

**Comment by laylaAbu** [comment]
how to build a card.md file?

sorry am a beginner in this Derek :(

**Comment by dsifford** [comment]
@laylaAbu No problem at all. We all were in your shoes at one point or another! 😄 

I'll let @jvoros describe that process to you. I think he might have a tutorial video or something handy that he used when helping another contributor.

**Comment by laylaAbu** [comment]
Thank you Thank you Thank you!

**Comment by jvoros** [comment]
The card looks great! Nice work.

There is a tutorial here on adding a card: https://github.com/aliemteam/aliemcards/wiki/Tutorial:-Adding-a-Card

It is not as straightforward as editing a card. I am working on a video tutorial to explain it as well, because I know it is difficult.

Take a look at that tutorial and let me know if it solves your problem. If not, we can do a video chat/screenshare.

**Comment by laylaAbu** [comment]
Thank you Jeremy

Layla


On Apr 20, 2017 2:14 PM, "Jeremy Voros" <notifications@github.com> wrote:

The card looks great! Nice work.

There is a tutorial here on adding a card: https://github.com/aliemteam/
aliemcards/wiki/Tutorial:-Adding-a-Card

It is not as straightforward as editing a card. I am working on a video
tutorial to explain it as well, because I know it is difficult.

Take a look at that tutorial and let me know if it solves your problem. If
not, we can do a video chat/screenshare.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aliemteam/aliemcards/pull/124#issuecomment-295841071>,
or mute the thread

**Comment by jvoros** [comment]
@laylaAbu I've updated the tutorials with some screencasts to hopefully clear it up. We're new to using this workflow too. So thanks for being a patient 'guinea pig' to help us figure out how to integrate the broader community.

Check out the Building a Card video here: https://github.com/aliemteam/aliemcards/wiki/How-to-Build-an-ALiEM-Card

And how to add a card here: https://github.com/aliemteam/aliemcards/wiki/Tutorial:-Adding-a-Card

**Comment by laylaAbu** [comment]
Thank you Jeremy!!
Looking at it now!

Layla

**Pull request closed without merging**
