### PR TITLE
Various changes/suggestions

### PR DESCRIPTION
**Pull request by dsifford**
**WIP - DO NOT MERGE**

**Changes:**
- Add yarn, editorconfig, and fix a couple things in server.js

### CODE REVIEW

**Comment by dsifford** [comment]
@jvoros 

## Some thoughts... (updated as thoughts come up)

### 1. Directory structure is non-optimal
- `bits` at best isn't descriptive and at worst reminds me of the term "naughty bits". Probably should rename that and break apart stuff within to a more sensible structure.
- `www` is an apache server convention. It is not a convention to any javascript project. I'd completely rename that to something that makes sense.
- Compiled code should **not** be in version control (webpack bundles, etc). Bad practice to do so.

**Comment by jvoros** [comment]
I like the cleanup.

I'm fine changing the `www` directory name. I come from PHP. So the apache way made sense. A little more descriptive than `src`, especially because this project has both the code to build the database and run the website, being clear about which items were made for the web seemed good.

I'll get webpack-dev-server set up. I had it in the other project. Used nodemon in a smaller test project, never did the necessary configuration here.

**Comment by dsifford** [comment]
> I'm fine changing the `www` directory name. I come from PHP. So the apache way made sense. A little more descriptive than `src`

Disagree. A JS developer with no PHP experience will have no idea what `www` means. Not a big deal; just a style thing. I only suggest `src` because I also think it would be wise to have a `dist` build directory (that is `.gitignore`ed).

**Comment by jvoros** [comment]
Hmmm. The gulp build script uses the schema file too. Maybe it should be in the top level. Also considering switching to Mongorito.js which doesn't require a schema.

I'm fine changing the `www` folder to a different name. Just explaining my thought process. How about `app`? I should put server and client side code into their own files too.

**Comment by dsifford** [comment]
It's your baby. Consider everything I say here to just be a suggestion. Ultimately, your decision for what you'd like to do.

What's wrong with the standard mongodb node package?

**Comment by jvoros** [comment]
I like the suggestions. I want to build a robust project, not just the hacky side projects I've done in the past.

MongoDB uses the schema, which seems weird in a mongo environment, which touts a schema-less db as a feature.

**Comment by dsifford** [comment]
I've used the standard mongodb driver in the past and I don't recall ever having to build schemas. Is this just a convenience feature?

**Comment by dsifford** [comment]
That way it'll pave the way for your unit tests as well.

**Comment by jvoros** [comment]
That's a good idea. I'm going to use `app` instead of `src`. Something about `src` bugs me ;)

**Comment by jvoros** [comment]
that is nice too because I am going to move the component styles to a module-style format with a separate style file for each component, imported with the React component. That structure will make it easy to build

**Comment by dsifford** [comment]
Have you seen [styled-components](https://github.com/styled-components/styled-components) or [styled-jsx](https://github.com/zeit/styled-jsx)? Either of those would be cool to play around with.

**Pull request merged**
